//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRouter.Gui.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XRouter.Gui.Service.IBrokerServiceForManagement")]
    public interface IBrokerServiceForManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerServiceForManagement/GetConfiguration", ReplyAction="http://tempuri.org/IBrokerServiceForManagement/GetConfigurationResponse")]
        XRouter.Common.ApplicationConfiguration GetConfiguration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerServiceForManagement/ChangeConfiguration", ReplyAction="http://tempuri.org/IBrokerServiceForManagement/ChangeConfigurationResponse")]
        void ChangeConfiguration(XRouter.Common.ApplicationConfiguration config);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrokerServiceForManagementChannel : XRouter.Gui.Service.IBrokerServiceForManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrokerServiceForManagementClient : System.ServiceModel.ClientBase<XRouter.Gui.Service.IBrokerServiceForManagement>, /*XRouter.Gui.Service.IBrokerServiceForManagement */ XRouter.Common.ComponentInterfaces.IBrokerServiceForManagement{
        
        public BrokerServiceForManagementClient() {
        }
        
        public BrokerServiceForManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrokerServiceForManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerServiceForManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerServiceForManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public XRouter.Common.ApplicationConfiguration GetConfiguration() {
            return base.Channel.GetConfiguration();
        }
        
        public void ChangeConfiguration(XRouter.Common.ApplicationConfiguration config) {
            base.Channel.ChangeConfiguration(config);
        }
    }
}
